services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 5432:5432
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hackme

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hackme
      ME_CONFIG_MONGODB_URL: mongodb://root:hackme@mongo:27017/