services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hackme

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hackme
      ME_CONFIG_MONGODB_URL: mongodb://root:hackme@mongo:27017/

  front:
    image: oven/bun
    build: ./worklance/apps/front
    volumes:
      - ./worklance/apps/front:/app/front
      - ./worklance/node_modules:/app/node_modules
      - ./worklance/packages:/app/packages
    ports:
      - "3000:3000"

  back:
    image: oven/bun
    build: ./worklance/apps/back
    env_file: ./worklance/.env
    ports:
      - "3001:3001"
    volumes:
      - ./worklance/apps/front:/app/back
      - ./worklance/node_modules:/app/node_modules
      - ./worklance/packages:/app/packages

